# Generated by Django 5.2.17 on 2026-10-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='barangay',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
